name: fast_order
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  mobile_scanner: ^3.3.0
  qr_flutter: ^4.1.0
  fl_chart: ^0.66.2
  intl: ^0.18.1
  uuid: ^3.0.7
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.0.0
  flutter_dotenv: ^5.2.1
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/imgs/logo_fast.png"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/imgs/logo_fast.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/imgs/logo_fast.png
    - assets/imgs/papels.jpg


